package ru.mail.network.utils.filter;

import com.huawei.hms.support.feature.result.CommonConstant;
import com.vk.accountmanager.data.AccountManagerRepositoryImpl;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import kotlin.jvm.internal.Intrinsics;
import org.jetbrains.annotations.NotNull;
import ru.mail.auth.TokenParser;
import ru.mail.authorizationsdk.feature.captcha.WebCaptchaComposeViewModel;
import ru.mail.logic.navigation.segue.ClickerLinkConstructor;
import ru.mail.util.log.Formats;
import ru.ok.android.sdk.SharedKt;

/* JADX INFO: compiled from: ProGuard */
/* JADX INFO: loaded from: classes15.dex */
@Metadata(d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0003\bÆ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003R\u0017\u0010\u0004\u001a\b\u0012\u0004\u0012\u00020\u00060\u0005¢\u0006\b\n\u0000\u001a\u0004\b\u0007\u0010\b¨\u0006\t"}, d2 = {"Lru/mail/network/utils/filter/LogFilters;", "", "<init>", "()V", "filters", "", "Lru/mail/util/log/Formats$ParamFormat;", "getFilters", "()Ljava/util/List;", "network-utils_release"}, k = 1, mv = {2, 2, 0}, xi = 48)
public final class LogFilters {

    @NotNull
    public static final LogFilters INSTANCE = new LogFilters();

    @NotNull
    private static final List<Formats.ParamFormat> filters;

    static {
        Formats.ParamFormat paramFormatNewUrlFormat = Formats.newUrlFormat("Authorization");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat = Formats.newJsonFormat("Authorization");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat = Formats.newUrlEncodedJsonFormat("Authorization");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat2 = Formats.newUrlFormat("SecretId");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat2, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat2 = Formats.newJsonFormat("SecretId");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat2, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat2 = Formats.newUrlEncodedJsonFormat("SecretId");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat2, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat3 = Formats.newUrlFormat("secretId");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat3, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat3 = Formats.newJsonFormat("secretId");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat3, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat3 = Formats.newUrlEncodedJsonFormat("secretId");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat3, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat4 = Formats.newUrlFormat("token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat4, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat4 = Formats.newJsonFormat("token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat4, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat4 = Formats.newUrlEncodedJsonFormat("token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat4, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat5 = Formats.newUrlFormat("Token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat5, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat5 = Formats.newJsonFormat("Token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat5, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat5 = Formats.newUrlEncodedJsonFormat("Token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat5, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat6 = Formats.newUrlFormat("webviewRefreshToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat6, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat6 = Formats.newJsonFormat("webviewRefreshToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat6, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat6 = Formats.newUrlEncodedJsonFormat("webviewRefreshToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat6, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat7 = Formats.newUrlFormat("webviewAccessToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat7, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat7 = Formats.newJsonFormat("webviewAccessToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat7, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat7 = Formats.newUrlEncodedJsonFormat("webviewAccessToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat7, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat8 = Formats.newUrlFormat("webviewAccessToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat8, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat8 = Formats.newJsonFormat("webviewAccessToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat8, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat8 = Formats.newUrlEncodedJsonFormat("webviewAccessToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat8, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat9 = Formats.newUrlFormat(AccountManagerRepositoryImpl.SECRET_ARG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat9, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat9 = Formats.newJsonFormat(AccountManagerRepositoryImpl.SECRET_ARG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat9, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat9 = Formats.newUrlEncodedJsonFormat(AccountManagerRepositoryImpl.SECRET_ARG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat9, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat10 = Formats.newUrlFormat(CommonConstant.KEY_ACCESS_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat10, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat10 = Formats.newJsonFormat(CommonConstant.KEY_ACCESS_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat10, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat10 = Formats.newUrlEncodedJsonFormat(CommonConstant.KEY_ACCESS_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat10, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat11 = Formats.newJsonFormat("LudwigToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat11, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat11 = Formats.newUrlFormat("LudwigToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat11, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat11 = Formats.newUrlEncodedJsonFormat("LudwigToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat11, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat12 = Formats.newUrlFormat("ludwigToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat12, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat12 = Formats.newJsonFormat("ludwigToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat12, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat12 = Formats.newUrlEncodedJsonFormat("ludwigToken");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat12, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat13 = Formats.newUrlFormat(WebCaptchaComposeViewModel.LUDWIG_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat13, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat13 = Formats.newJsonFormat(WebCaptchaComposeViewModel.LUDWIG_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat13, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat13 = Formats.newUrlEncodedJsonFormat(WebCaptchaComposeViewModel.LUDWIG_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat13, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat14 = Formats.newUrlFormat("email");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat14, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat14 = Formats.newJsonFormat("email");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat14, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat14 = Formats.newUrlEncodedJsonFormat("email");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat14, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat15 = Formats.newUrlFormat("Email");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat15, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat15 = Formats.newJsonFormat("Email");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat15, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat15 = Formats.newUrlEncodedJsonFormat("Email");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat15, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat16 = Formats.newUrlFormat("login");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat16, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat16 = Formats.newJsonFormat("login");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat16, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat16 = Formats.newUrlEncodedJsonFormat("login");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat16, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat17 = Formats.newUrlFormat("Login");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat17, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat17 = Formats.newJsonFormat("Login");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat17, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat17 = Formats.newUrlEncodedJsonFormat("Login");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat17, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat18 = Formats.newUrlFormat("password");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat18, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat18 = Formats.newJsonFormat("password");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat18, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat18 = Formats.newUrlEncodedJsonFormat("password");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat18, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat19 = Formats.newUrlFormat("Password");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat19, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat19 = Formats.newJsonFormat("Password");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat19, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat19 = Formats.newUrlEncodedJsonFormat("Password");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat19, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat20 = Formats.newUrlFormat("pass");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat20, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat20 = Formats.newJsonFormat("pass");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat20, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat20 = Formats.newUrlEncodedJsonFormat("pass");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat20, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat21 = Formats.newUrlFormat("code");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat21, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat21 = Formats.newJsonFormat("code");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat21, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat21 = Formats.newUrlEncodedJsonFormat("code");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat21, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat22 = Formats.newUrlFormat(ClickerLinkConstructor.AUTOGEN_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat22, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat22 = Formats.newJsonFormat(ClickerLinkConstructor.AUTOGEN_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat22, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat22 = Formats.newUrlEncodedJsonFormat(ClickerLinkConstructor.AUTOGEN_TOKEN);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat22, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat23 = Formats.newJsonFormat("access_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat23, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat23 = Formats.newUrlFormat("access_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat23, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat23 = Formats.newUrlEncodedJsonFormat("access_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat23, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat24 = Formats.newJsonFormat("refresh_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat24, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat24 = Formats.newUrlFormat("refresh_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat24, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat24 = Formats.newUrlEncodedJsonFormat("refresh_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat24, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat25 = Formats.newJsonFormat("Access_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat25, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat25 = Formats.newUrlFormat("Access_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat25, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat25 = Formats.newUrlEncodedJsonFormat("Access_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat25, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat26 = Formats.newJsonFormat("Refresh_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat26, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat26 = Formats.newUrlFormat("Refresh_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat26, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat26 = Formats.newUrlEncodedJsonFormat("Refresh_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat26, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat27 = Formats.newJsonFormat(TokenParser.SIGN_SENTMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat27, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat27 = Formats.newUrlEncodedJsonFormat(TokenParser.SIGN_SENTMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat27, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat28 = Formats.newJsonFormat(TokenParser.TOKEN_SENTMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat28, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat28 = Formats.newUrlEncodedJsonFormat(TokenParser.TOKEN_SENTMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat28, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat29 = Formats.newJsonFormat(TokenParser.SIGN_MOVEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat29, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat29 = Formats.newUrlEncodedJsonFormat(TokenParser.SIGN_MOVEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat29, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat30 = Formats.newJsonFormat(TokenParser.TOKEN_MOVEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat30, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat30 = Formats.newUrlEncodedJsonFormat(TokenParser.TOKEN_MOVEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat30, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat31 = Formats.newJsonFormat(TokenParser.SIGN_BOUNCEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat31, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat31 = Formats.newUrlEncodedJsonFormat(TokenParser.SIGN_BOUNCEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat31, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat32 = Formats.newJsonFormat(TokenParser.TOKEN_BOUNCEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat32, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat32 = Formats.newUrlEncodedJsonFormat(TokenParser.TOKEN_BOUNCEMSG);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat32, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat33 = Formats.newJsonFormat("bind_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat33, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat27 = Formats.newUrlFormat("bind_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat27, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat33 = Formats.newUrlEncodedJsonFormat("bind_token");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat33, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat34 = Formats.newJsonFormat(SharedKt.PARAM_CLIENT_SECRET);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat34, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat28 = Formats.newUrlFormat(SharedKt.PARAM_CLIENT_SECRET);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat28, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat34 = Formats.newUrlEncodedJsonFormat(SharedKt.PARAM_CLIENT_SECRET);
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat34, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat35 = Formats.newJsonFormat("Client_secret");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat35, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat29 = Formats.newUrlFormat("Client_secret");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat29, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat35 = Formats.newUrlEncodedJsonFormat("Client_secret");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat35, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat30 = Formats.newUrlFormat("Mpop");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat30, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat36 = Formats.newJsonFormat("Mpop");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat36, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat36 = Formats.newUrlEncodedJsonFormat("Mpop");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat36, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat31 = Formats.newUrlFormat("mrcu");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat31, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat37 = Formats.newJsonFormat("mrcu");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat37, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat37 = Formats.newUrlEncodedJsonFormat("mrcu");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat37, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat32 = Formats.newUrlFormat("Set-cookie");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat32, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat38 = Formats.newJsonFormat("Set-cookie");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat38, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat38 = Formats.newUrlEncodedJsonFormat("Set-cookie");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat38, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat33 = Formats.newUrlFormat("set-cookie");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat33, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat39 = Formats.newJsonFormat("set-cookie");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat39, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat39 = Formats.newUrlEncodedJsonFormat("set-cookie");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat39, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat40 = Formats.newJsonFormat("phone_number");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat40, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat34 = Formats.newUrlFormat("phone_number");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat34, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat40 = Formats.newUrlEncodedJsonFormat("phone_number");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat40, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat41 = Formats.newJsonFormat("phone");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat41, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat35 = Formats.newUrlFormat("phone");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat35, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat41 = Formats.newUrlEncodedJsonFormat("phone");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat41, "newUrlEncodedJsonFormat(...)");
        Formats.ParamFormat paramFormatNewJsonFormat42 = Formats.newJsonFormat("Phone");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewJsonFormat42, "newJsonFormat(...)");
        Formats.ParamFormat paramFormatNewUrlFormat36 = Formats.newUrlFormat("Phone");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlFormat36, "newUrlFormat(...)");
        Formats.ParamFormat paramFormatNewUrlEncodedJsonFormat42 = Formats.newUrlEncodedJsonFormat("Phone");
        Intrinsics.checkNotNullExpressionValue(paramFormatNewUrlEncodedJsonFormat42, "newUrlEncodedJsonFormat(...)");
        filters = CollectionsKt.listOf((Object[]) new Formats.ParamFormat[]{paramFormatNewUrlFormat, paramFormatNewJsonFormat, paramFormatNewUrlEncodedJsonFormat, paramFormatNewUrlFormat2, paramFormatNewJsonFormat2, paramFormatNewUrlEncodedJsonFormat2, paramFormatNewUrlFormat3, paramFormatNewJsonFormat3, paramFormatNewUrlEncodedJsonFormat3, paramFormatNewUrlFormat4, paramFormatNewJsonFormat4, paramFormatNewUrlEncodedJsonFormat4, paramFormatNewUrlFormat5, paramFormatNewJsonFormat5, paramFormatNewUrlEncodedJsonFormat5, paramFormatNewUrlFormat6, paramFormatNewJsonFormat6, paramFormatNewUrlEncodedJsonFormat6, paramFormatNewUrlFormat7, paramFormatNewJsonFormat7, paramFormatNewUrlEncodedJsonFormat7, paramFormatNewUrlFormat8, paramFormatNewJsonFormat8, paramFormatNewUrlEncodedJsonFormat8, paramFormatNewUrlFormat9, paramFormatNewJsonFormat9, paramFormatNewUrlEncodedJsonFormat9, paramFormatNewUrlFormat10, paramFormatNewJsonFormat10, paramFormatNewUrlEncodedJsonFormat10, paramFormatNewJsonFormat11, paramFormatNewUrlFormat11, paramFormatNewUrlEncodedJsonFormat11, paramFormatNewUrlFormat12, paramFormatNewJsonFormat12, paramFormatNewUrlEncodedJsonFormat12, paramFormatNewUrlFormat13, paramFormatNewJsonFormat13, paramFormatNewUrlEncodedJsonFormat13, paramFormatNewUrlFormat14, paramFormatNewJsonFormat14, paramFormatNewUrlEncodedJsonFormat14, paramFormatNewUrlFormat15, paramFormatNewJsonFormat15, paramFormatNewUrlEncodedJsonFormat15, paramFormatNewUrlFormat16, paramFormatNewJsonFormat16, paramFormatNewUrlEncodedJsonFormat16, paramFormatNewUrlFormat17, paramFormatNewJsonFormat17, paramFormatNewUrlEncodedJsonFormat17, paramFormatNewUrlFormat18, paramFormatNewJsonFormat18, paramFormatNewUrlEncodedJsonFormat18, paramFormatNewUrlFormat19, paramFormatNewJsonFormat19, paramFormatNewUrlEncodedJsonFormat19, paramFormatNewUrlFormat20, paramFormatNewJsonFormat20, paramFormatNewUrlEncodedJsonFormat20, paramFormatNewUrlFormat21, paramFormatNewJsonFormat21, paramFormatNewUrlEncodedJsonFormat21, paramFormatNewUrlFormat22, paramFormatNewJsonFormat22, paramFormatNewUrlEncodedJsonFormat22, paramFormatNewJsonFormat23, paramFormatNewUrlFormat23, paramFormatNewUrlEncodedJsonFormat23, paramFormatNewJsonFormat24, paramFormatNewUrlFormat24, paramFormatNewUrlEncodedJsonFormat24, paramFormatNewJsonFormat25, paramFormatNewUrlFormat25, paramFormatNewUrlEncodedJsonFormat25, paramFormatNewJsonFormat26, paramFormatNewUrlFormat26, paramFormatNewUrlEncodedJsonFormat26, paramFormatNewJsonFormat27, paramFormatNewUrlEncodedJsonFormat27, paramFormatNewJsonFormat28, paramFormatNewUrlEncodedJsonFormat28, paramFormatNewJsonFormat29, paramFormatNewUrlEncodedJsonFormat29, paramFormatNewJsonFormat30, paramFormatNewUrlEncodedJsonFormat30, paramFormatNewJsonFormat31, paramFormatNewUrlEncodedJsonFormat31, paramFormatNewJsonFormat32, paramFormatNewUrlEncodedJsonFormat32, paramFormatNewJsonFormat33, paramFormatNewUrlFormat27, paramFormatNewUrlEncodedJsonFormat33, paramFormatNewJsonFormat34, paramFormatNewUrlFormat28, paramFormatNewUrlEncodedJsonFormat34, paramFormatNewJsonFormat35, paramFormatNewUrlFormat29, paramFormatNewUrlEncodedJsonFormat35, paramFormatNewUrlFormat30, paramFormatNewJsonFormat36, paramFormatNewUrlEncodedJsonFormat36, paramFormatNewUrlFormat31, paramFormatNewJsonFormat37, paramFormatNewUrlEncodedJsonFormat37, paramFormatNewUrlFormat32, paramFormatNewJsonFormat38, paramFormatNewUrlEncodedJsonFormat38, paramFormatNewUrlFormat33, paramFormatNewJsonFormat39, paramFormatNewUrlEncodedJsonFormat39, paramFormatNewJsonFormat40, paramFormatNewUrlFormat34, paramFormatNewUrlEncodedJsonFormat40, paramFormatNewJsonFormat41, paramFormatNewUrlFormat35, paramFormatNewUrlEncodedJsonFormat41, paramFormatNewJsonFormat42, paramFormatNewUrlFormat36, paramFormatNewUrlEncodedJsonFormat42});
    }

    private LogFilters() {
    }

    @NotNull
    public final List<Formats.ParamFormat> getFilters() {
        return filters;
    }
}
